version: "3.8"
services:
  cimov2:
    image: cimo-app
    build:
      context: .
    ports:
      - "5000:5000"
    container_name: CimoV2
    restart: unless-stopped
    env_file:
      - .env
